@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Alternative One

autonumber

actor "Green Spaces Manager" as Employee
participant ":System" as System

activate Employee

    Employee -> System : asks to add a task to the To-Do List
    activate System

        System --> Employee : requests data (reference, description, duration, urgency degree, green space)
    deactivate System

    Employee -> System : types requested data and presses the "Add" button
    activate System

        System --> Employee : verifies data

        System --> Employee : submits data and displays operation success
    deactivate System

@enduml