@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Alternative One

autonumber

actor "Green Space Manager" as Employee
participant ":System" as System

activate Employee

    Employee -> System : asks to Green Space
    activate System

        System --> Employee : requests for the respective area of green space
    deactivate System

    Employee -> System : types requested data

    activate System

        System --> Employee : shows the area and requests confirmation
    deactivate System


    Employee -> System : confirms area
    activate System

    System -> Employee : asks about the type of space

    Employee -> System : select type

        System --> Employee : displays operation success
    deactivate System

@enduml