@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Alternative One

autonumber

actor "Human Resources\nManager" as Employee
participant ":System" as System

activate Employee

    Employee -> System : asks to create a new job
    activate System

        System --> Employee : requests data (i.e. Job name, small description, set of skills needed)
    deactivate System

    Employee -> System : types requested data
    activate System

        System --> Employee : Shows a confirmation message and present a list of possible candidates based on the skills
    deactivate System



@enduml