@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
'skinparam linetype ortho
'left to right direction
skinparam classAttributeIconSize 0
hide circle
hide methods

'title Domain Model

'class Platform {
'  -description
'}
class Organization{
    name
}

class HRM{
    name
    email
    phone number
    identification document
}

class VFM{
    name
    email
    phone number
    identification document
}

class GSM{
    name
    email
    phone number
    identification document
}

class GSU{
    name
    email
    phone number
    identification document
}

class QAM{
    name
    email
    phone number
    identification document
}

class Skill{
    name
}

class Job{
    name
}

class Collaborator{
    name
    birth details
    issuing details
    address
    phone number
    email
    identification document
}

class Team

class Task{
    name
    urgency
    expected duration
    status
}

class Vehicle{
    Brand
    Model
    Type
    Tare
    Gross Weight
    Current Km
    Register Date
    Acquisition Date
    Maintenance/Check-up
}

class Check-up{
    distance "km"
}

class Check-upList{
    Vehicles needing check-up
}

class ToDoList{
    task description
    urgency
    expected duration
}

class Agenda{
    task description
    team
    vehicles/equipment
    expected duration
    status
}

Organization -- "*" HRM : is a part of <
Organization -- "*" VFM : is a part of <
Organization -- "*" GSM : is a part of <
Organization -- "*" GSU : is a part of <
Organization -- "*" QAM : is a part of <
Organization -- Vehicle : owns >
HRM "1" -- "*" Skill : registers >
HRM "1" -- "*" Job : registers >
HRM "1" -- "*" Collaborator : registers >
Collaborator "1" -- "*" Skill : has a set of >
Collaborator "1" -- "1" Job : has >
Collaborator "*" -- "1" Team : generates >
Team "1" -- "*" Task : is assigned a >
VFM "1" -- "*" Vehicle : registers >
VFM "1" -- "*" "Check-up" : registers >
Vehicle "1" -- "0..1" "Check-up" : needs >
Team "1" -- "0..*" Vehicle : needs >
"Check-upList" "1" -- "*" "Check-up" :  creates <
GSM "1" -- "*" ToDoList : has >
ToDoList "1" -- "*" Task : includes >
Agenda "1" -- "*" Task : schedules >
Agenda "1" -- "*" Team : assigns >
Agenda "1" -- "*" Vehicle : uses >

@enduml
