@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "Green Space Manager " as ADM
participant ":CreateGreenSpaceUI" as UI
participant ":CreateGreenSpaceController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "GreenSpaceRepository:\nGreenSpaceRepository" as TaskCategoryRepository


activate ADM

        ADM -> UI : asks to register a Green Space

        activate UI

'            UI --> ADM : requests data (reference, description,  informal \n description, technical description, duration, cost)
            'create CTRL
            UI -> CTRL** : create

            UI -> CTRL : getGreenSpace
            activate CTRL

                CTRL -> RepositorySingleton : getInstance()
                activate RepositorySingleton

                    RepositorySingleton --> CTRL: repositories
                deactivate RepositorySingleton

                CTRL -> TaskCategoryRepository : getGreenSpaceRepository()
                activate TaskCategoryRepository

                    TaskCategoryRepository --> CTRL: greenSpaceRepository
                deactivate TaskCategoryRepository



                CTRL --> UI : GreenSpaceRegister
            deactivate CTRL

            UI --> ADM : requests for the respective area of green space
        deactivate UI

    ADM -> UI : types requested area
    activate UI

        UI --> ADM : asks about the type of space
    deactivate UI

    ADM -> UI : select the type
    activate UI

    UI -> ADM :shows the area and type and requests confirmation
    deactivate UI


    ADM ->UI : confirms the area and type
    activate UI

    UI -> TaskCategoryRepository : registerGreenSpace



        activate TaskCategoryRepository

        TaskCategoryRepository --> UI : GreenSpace


        deactivate  TaskCategoryRepository

            deactivate CTRL
            UI --> ADM: displays operation success
    deactivate UI

deactivate ADM

@enduml