@startuml
'skinparam monochrome true
skinparam packageStyle rectangle
'skinparam shadowing false

skinparam rectangle{
    BorderColor white
}

'title Use Case Diagram Example

left to right direction

rectangle " " as actors {
    actor "Human Resources Manager" as Freelancer
    actor "Fleet Manager" as Employee
}

rectangle " " as usecases{
    usecase "UC1 - Register skills" as UC1
    usecase "UC2 - Register a job" as UC2
    usecase "UC3 - Register a collaborator" as UC3
    usecase "UC4 - Assign skills" as UC4
    usecase "UC5 - Generate team proposal" as UC5
    Freelancer --> UC1
    Freelancer --> UC2
    Freelancer --> UC3
    Freelancer --> UC4
    Freelancer --> UC5
    usecase "UC6 - Register a vehicle" as UC6
    usecase "UC7 - Register a vehicle’s check-up" as UC7
    usecase "UC8 - List vehicles in need for a check-up" as UC8
    Employee --> UC6
    Employee --> UC7
    Employee --> UC8


@enduml