@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Alternative One

autonumber

actor "Green Space Manager" as Employee
participant ":System" as System

activate Employee

    Employee -> System : asks for agenda
    activate System

        System --> Employee : shows agenda
    deactivate System

    Employee -> System : asks to postpone an entry
    activate System

        System --> Employee : shows the calendar and asks what the new date is
    deactivate System

    Employee -> System : choose the date
    activate System

        System --> Employee : confirm availability and display success message
    deactivate System

@enduml