@startuml
'skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam linetype polyline
'skinparam linetype orto

skinparam classAttributeIconSize 0

'left to right direction

' vehicle Repository !!!1
class agendaRepository{
    +getVehicleRepository
    +registerVehicle
}

class AssignTeamToEntryUI{

}

class Repositories {
    - Repositories()
    + getInstance() : Repositories
    + agendaRepository()
}

class AgendaController{


}

class GSM{
    name
    email
    phone number
    identification document
}


class Entry{
    entryID
        task
        dueDate
        status
}



AssignTeamToEntryUI --> AgendaController
Repositories --> agendaRepository
AgendaController --> Repositories
agendaRepository --> Agenda
AgendaController --> Agenda
Entry "1" -- "*" Agenda : saved in >
Team "1" -- "*" Agenda : saved in >
GSM "1" -- "*" Entry : registers >
GSM "1" -- "*" "Team" : assigns >



@enduml