@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Alternative One

autonumber

actor "Fleet Manager" as Employee
participant ":System" as System

activate Employee

    Employee -> System : asks  to list the vehicles needing the check-up
    activate System


        System --> Employee : shows the list with the vehicles needing the check-up
    deactivate System


        System --> Employee : displays operation success
    deactivate System

@enduml