@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "Green spaces manager" as ADM
participant ":ToDoListUI" as UI
participant ":ToDoListController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "greenSpaceRepository:\nGreenSpaceRepository" as GreenSpaceRepository
participant "GreenSpacesController \n:GreenSpacesController" as Controller
participant "toDoList\n :ToDoList" as ToDoList
participant "task\n:Task" as Task


activate ADM

    ADM -> UI : asks to add a new entry to the To-Do List

        activate UI

        UI -> CTRL** : create
        UI ->CTRL: listGreenSpaces()
                activate CTRL

                CTRL -> CTRL: getGreenSpaceRepository
                activate CTRL



                 CTRL -> RepositorySingleton : getInstance()
                                        activate RepositorySingleton

                                        RepositorySingleton -> CTRL : repositories
                                        deactivate RepositorySingleton

                                        CTRL -> PLAT : getGreenSpaceRepository()
                                        activate PLAT

                                        PLAT --> CTRL : greenSpaceRepository
                                        deactivate PLAT
                                        deactivate CTRL
                                        CTRL-> GreenSpaceRepository: getGreenSpaces()
                                        activate GreenSpaceRepository
                                        GreenSpaceRepository --> CTRL: greenSpaces
                                        deactivate GreenSpaceRepository
                                        CTRL -->UI: greenSpaces

                                        CTRL ->Controller: toDTO(greenSpaces)
                                        activate Controller
                                        ref over Controller
                                            List
                                        end ref

                                        Controller --> CTRL: greenSpaces
                                        deactivate Controller

                                        CTRL --> UI: greenSpaces
                                        deactivate CTRL

        UI --> ADM : requests the name and description of the task,\n the degree of urgency and the approximate\n expected duration, shows the list of green spaces \n and asks to select the desired green space

        deactivate UI

    ADM -> UI : types the name and description of the task, the \n degree of urgency and the approximate\n expected duration and selects the desired green space


            activate UI

            UI->CTRL: registerTask(taskName, taskDescription, taskUrgency, taskFinalDuration, greenSpaceName)
            activate CTRL
            CTRL -> CTRL: getGreenSpaceRepository
                            activate CTRL



                             CTRL -> RepositorySingleton : getInstance()
                              activate RepositorySingleton

                              RepositorySingleton -> CTRL : repositories
                              deactivate RepositorySingleton

                              CTRL -> PLAT : getGreenSpaceRepository()
                              activate PLAT

                              PLAT --> CTRL : greenSpaceRepository
                              deactivate PLAT
                              deactivate CTRL


                CTRL -> CTRL: getToDoList
                activate CTRL

                 CTRL -> RepositorySingleton : getInstance()
                                        activate RepositorySingleton

                                        RepositorySingleton -> CTRL : repositories
                                        deactivate RepositorySingleton

                                        CTRL -> PLAT : getToDoList()
                                        activate PLAT

                                        PLAT --> CTRL : toDoList
                                        deactivate PLAT
                                        deactivate CTRL

                                        CTRL -> GreenSpaceRepository: getGreenSpaceByName(greenSpaceName)
                                        activate GreenSpaceRepository

                                        GreenSpaceRepository --> CTRL: verifiedGreenSpace
                                        deactivate GreenSpaceRepository

                         CTRL ->ToDoList: registerTask(name, description, urgency, duration, verifiedGreenSpace)
                                    activate ToDoList

                                    ToDoList -> Task**: registerTask(name, description, urgency, duration, GreenSpace)
                                    ToDoList ->ToDoList:add(ToDoEntry)
                                    activate ToDoList
                                    ToDoList ->ToDoList: validateEntry(ToDoEntry)
                                    activate ToDoList
                                    ToDoList -->ToDoList
                                    deactivate ToDoList
                                    ToDoList -->ToDoList
                                    deactivate ToDoList

                                    ToDoList -->CTRL
                                    deactivate ToDoList


        CTRL --> UI

            deactivate CTRL

        UI --> ADM : shows operation success message and\n displays the registered green spaces

    deactivate UI

deactivate ADM

@enduml