@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "Green Space Manager" as ADM
participant ":AgendaUI" as UI
participant ":CreateAgendaController" as CTRL
participant ":Repositories" as RepositorySingleton

participant "AgendaRepository" as Agenda

activate ADM

        ADM -> UI : asks for agenda

        activate UI


                       'create CTRL
                        UI -> CTRL** : create

                        UI -> CTRL : getAgenda
                        activate CTRL

                            CTRL -> RepositorySingleton : getInstance()
                            activate RepositorySingleton

                                RepositorySingleton --> CTRL: repositories
                            deactivate RepositorySingleton

                            CTRL -> Agenda : getAgendaRepository()
                            activate Agenda

                                Agenda --> CTRL: agendaRepository
                            deactivate Agenda



                            CTRL --> UI : Agenda
                    deactivate CTRL

            UI --> ADM : shows agenda
        deactivate UI

    ADM -> UI : asks to postpone an entry
    activate UI

        UI --> ADM : asks what the new date is


    ADM -> UI : choose the date

    UI --> CTRL : newDate
        activate CTRL

        CTRL -->Agenda : getDateInformation

        activate Agenda

        Agenda --> CTRL : dateConfirmation

        deactivate Agenda

        CTRL --> UI : dateConfirmation

            deactivate CTRL
            UI --> ADM: confirm availability and display success message

    deactivate UI

deactivate ADM

@enduml