@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
'skinparam linetype ortho
'left to right direction
skinparam classAttributeIconSize 0
hide circle
hide methods

'title Domain Model

'class Platform {
'  -description
'}


class GSM{
    name
    email
    phone number
    identification document
}
class Entry{
Name
Task to assign
due date
status
}

class Team{
Collaborators
}






GSM "1" -- "*" Entry : selects >
GSM "1" -- "*" "Team" : assigns >


@enduml