@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
'skinparam linetype ortho
'left to right direction
skinparam classAttributeIconSize 0
hide circle
hide methods

'title Domain Model

'class Platform {
'  -description
'}


class GSM{
    name
    email
    phone number
    identification document
}


class Agenda{

}
class entry{
 entryID
    task
    dueDate
    status
}



GSM "1" -- "*" entry : can cancel an  >
Agenda "1" -- "*" "entry" : made of >
GSM "1" -- "1" "Agenda" : manages >


@enduml