@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "Collaborator" as Col
participant ":TaskRecorder" as Recorder
participant ":Task" as T
participant ":TaskCompletion" as TC

activate Col

        Col -> Recorder : records task completion

        activate Recorder

            Recorder -> T : get task details
            activate T

                T --> Recorder : task details
            deactivate T

            Recorder -> TC : recordTaskCompletion(taskID, completionNotes)
            activate TC

                TC --> Recorder : completion record
            deactivate TC

            Recorder --> Col : displays operation success
        deactivate Recorder

deactivate Col

@enduml
