@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Alternative One

autonumber

actor "Green Space Manager" as Employee
participant ":System" as System

activate Employee

    Employee -> System : asks for agenda
    activate System

        System --> Employee : requests the list of available vehicles from the Vehicle Inventory
    deactivate System

    Employee -> System :
    activate System

        System --> Employee : returns the list of available vehicles
    deactivate System

    Employee -> System : confirms data
    activate System

        System --> Employee : displays operation success
    deactivate System

@enduml