@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Alternative One

autonumber

actor "Green Space Manager" as Employee
participant ":System" as System

activate Employee

    Employee -> System : asks for agenda
    activate System

        System --> Employee : shows agenda
    deactivate System

    Employee -> System : asks about the list of available vehicles
    activate System

        System --> Employee : returns the list of available vehicles
    deactivate System

    Employee -> System : assign one or more vehicles to an entry
    activate System

        System --> Employee : confirm and display success message
    deactivate System

@enduml