@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "Human Resources Manager" as ADM
participant ":CreateJobUI" as UI
participant ":CreateJobController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "jobRepository:\njobRepository" as TaskCategoryRepository





activate ADM

        ADM -> UI : asks to register a vehicle

        activate UI

'            UI --> ADM : requests data (reference, description,  informal \n description, technical description, duration, cost)
            'create CTRL
            UI -> CTRL** : create

            UI -> CTRL : getVehicle
            activate CTRL

                CTRL -> RepositorySingleton : getInstance()
                activate RepositorySingleton

                    RepositorySingleton --> CTRL: repositories
                deactivate RepositorySingleton

                CTRL -> TaskCategoryRepository : getVehicleRepository()
                activate TaskCategoryRepository

                    TaskCategoryRepository --> CTRL: vehicleRepository
                deactivate TaskCategoryRepository



                CTRL --> UI : vehicleRegister
            deactivate CTRL

            UI --> ADM : requests data (Brand, Model, Type, Tare, Gross Weight ,\n Current Km, Register Date, Acquisition Date,\n Maintenance/Check- up Frequency (in Kms))
        deactivate UI

    ADM -> UI : types requested data
    activate UI

        UI --> ADM : shows all data and requests confirmation
    deactivate UI

    ADM -> UI : confirms data
    activate UI

    UI -> TaskCategoryRepository : registerVehicle

        activate TaskCategoryRepository

        TaskCategoryRepository --> UI : Vehicle


        deactivate  TaskCategoryRepository

            deactivate CTRL
            UI --> ADM: displays operation success
    deactivate UI

deactivate ADM

@enduml