@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

participant ":RegisterVehicleCheckUpController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "vehicleRepository:\nVehicleRepository" as VehicleRepository

autonumber 4

-> CTRL : getVehicleByLicensePlate(vehicleLicensePlate)
activate CTRL
group Get vehicle
CTRL -> RepositorySingleton : getInstance()
activate RepositorySingleton
RepositorySingleton --> CTRL: repositories
deactivate RepositorySingleton

CTRL -> PLAT : getVehicleRepository()
activate PLAT
PLAT --> CTRL: VehicleRepository
deactivate PLAT

CTRL -> VehicleRepository : getVehicleByLicensePlate(vehicleLicensePlate)
activate VehicleRepository
VehicleRepository --> CTRL: vehicle
deactivate VehicleRepository
end
<- CTRL  : vehicle


@enduml