@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Alternative One

autonumber

actor "Collaborator" as Employee
participant ":System" as System

activate Employee

    Employee -> System : asks to record the completion of a task
    activate System

        System --> Employee : shows the To-Do List with all the tasks and asks to select one or more
    deactivate System

    Employee -> System : selects ths task(s)
    activate System

        System --> Employee : shows the task(s) selected and requests confirmation
    deactivate System

    Employee -> System : confirms data
    activate System

        System --> Employee : displays operation success
    deactivate System

@enduml