@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "Human Resources Manager" as ADM
participant ":CreateVehicleUI" as UI
participant ":CreateVehicleController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "VehicleRepository:\nVehicleRepository" as TaskCategoryRepository


activate ADM

        ADM -> UI : asks for agenda

        activate UI

'            UI --> ADM : requests data (reference, description,  informal \n description, technical description, duration, cost)
            'create CTRL
            UI -> CTRL** : create

            UI -> CTRL : getVehicle
            activate CTRL

                CTRL -> RepositorySingleton : getInstance()
                activate RepositorySingleton

                    RepositorySingleton --> CTRL: repositories
                deactivate RepositorySingleton

                CTRL -> TaskCategoryRepository : getVehicleRepository()
                activate TaskCategoryRepository

                    TaskCategoryRepository --> CTRL: vehicleRepository
                deactivate TaskCategoryRepository



                CTRL --> UI : vehicleRegister
            deactivate CTRL

            UI --> ADM : shows agenda
        deactivate UI

    ADM -> UI : asks about the list of available vehicles
    activate UI

        UI --> ADM : returns the list of available vehicles
    deactivate UI

    ADM -> UI : assign one or more vehicles to an entry
    activate UI

    UI -> TaskCategoryRepository : registerVehicle

        activate TaskCategoryRepository

        TaskCategoryRepository --> UI : Vehicle


        deactivate  TaskCategoryRepository

            deactivate CTRL
            UI --> ADM:  confirm and display success message
    deactivate UI

deactivate ADM

@enduml