@startuml
'skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam linetype polyline
'skinparam linetype orto

skinparam classAttributeIconSize 0

'left to right direction

' vehicle Repository !!!1
class VehicleRepository{
    +getVehicleRepository
    +addVehicle
}

class AgendaUI{

}
class AgendaRepository{
    +getAgendaRepository
}

class Repositories {
    - Repositories()
    + getInstance() : Repositories
    + getVehicleRepository()
    +getAgendaRepository
}

class AgendaController{
    +getAgenda

}

class GSM{
    name
    email
    phone number
    identification document
}


class Vehicle{
    Brand
    Model
    Type
    Tare
    Gross Weight
    Current Km
    Register Date
    Acquisition Date
    Maintenance/Check-up
}
class Agenda {
}



AgendaUI --> AgendaController
Repositories --> VehicleRepository
AgendaController --> Repositories
AgendaController --> Agenda
VehicleRepository --> Vehicle
AgendaController --> Vehicle
GSM "1" -- "*" Agenda : registers >
Repositories --> AgendaRepository



@enduml